export default {
    Desafio_En_progreso: 1,
    Desafio_En_evaluacion: 2,
    Desafio_En_espera_de_entrega_de_premios: 3,
    Desafio_Finalizado: 4,
    Desafio_Cancelado: 5,
    Proceso_de_Evaluacion_No_iniciado: 10,
    Proceso_de_Evaluacion_En_progreso: 11,
    Proceso_de_Evaluacion_Finalizado: 12,
    Solucion_Enviada: 13,
    Solucion_Descartada: 14,
    Solucion_Incompleta: 15,
    Solucion_Evaluada: 16,
    Soporte_Enviada: 17,
    Soporte_En_progreso: 18,
    Soporte_Finalizada: 19,
    Soporte_Descartada: 20,
    Desafio_Sin_iniciar: 21,
    Desafio_Sin_validar: 22,
    Desafio_Rechazado: 23,
    Desafio_Descartado: 25
};
