// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class Adjuntos
{
    public int idAdjunto { get; set; }

    public int idProceso { get; set; }

    public string Nombre { get; set; }

    public string ContentType { get; set; }

    public long Tamaño { get; set; }

    public DateTime FechaSubida { get; set; }

    public string RutaArchivo { get; set; }

    public int? idUsuario { get; set; }
}