// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class ComentariosProceso
{
    public int idComentario { get; set; }

    public int idProceso { get; set; }

    public int idUsuario { get; set; }

    public string Comentario { get; set; }

    public int? idComentarioPadre { get; set; }
}