// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class CredencialesAutenticacion
{
    public int idCredencial { get; set; }

    public int idUsuario { get; set; }

    public int idMetodoAutenticacion { get; set; }

    public string idExterno { get; set; }

    public string TokenAcceso { get; set; }
}