// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class Desafios
{
    public int idDesafio { get; set; }

    public int idEmpresa { get; set; }

    public string Titulo { get; set; }

    public string Contenido { get; set; }

    public DateTime FechaRegistro { get; set; }

    public DateTime FechaLimite { get; set; }
}