// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class DesafiosCategoria
{
    public int idDesafioCategoria { get; set; }

    public int idDesafio { get; set; }

    public int idCategoria { get; set; }
}