// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class Empresas
{
    public int idEmpresa { get; set; }

    public int idUsuario { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string PaginaWeb { get; set; }

    public int idTamañoEmpresa { get; set; }

    public int idSector { get; set; }

    public string Direccion { get; set; }
}