// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class EstatusProceso
{
    public int idEstatusProceso { get; set; }

    public int idClaseProceso { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public bool RequiereMotivo { get; set; }

    public bool Activo { get; set; }

    public string Severidad { get; set; }

    public string ClaseIcono { get; set; }
}