// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class Identificaciones
{
    public int idIdentificacion { get; set; }

    public int idUsuario { get; set; }

    public int idTipoIdentificacion { get; set; }

    public string Valor { get; set; }
}