// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class LogActividades
{
    public int idLogActividad { get; set; }

    public int idUsuario { get; set; }

    public string Metodo { get; set; }

    public string URL { get; set; }

    public string Data { get; set; }

    public DateTime Fecha { get; set; }
}