// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class LogErrores
{
    public int idLogError { get; set; }

    public int idUsuario { get; set; }

    public string Mensaje { get; set; }

    public string Fuente { get; set; }

    public string StackTrace { get; set; }

    public DateTime Fecha { get; set; }
}