// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class NivelesEducativo
{
    public int idNivelEducativo { get; set; }

    public string Nombre { get; set; }
}