// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class Participantes
{
    public int idParticipante { get; set; }

    public int idUsuario { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public int idNivelEducativo { get; set; }

    public string DescripcionPersonal { get; set; }
}