// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class ProcesoEvaluacion
{
    public int idProcesoEvaluacion { get; set; }

    public int idDesafio { get; set; }

    public int idTipoEvaluacion { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime FechaFinalizacion { get; set; }
}