// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class Soluciones
{
    public int idSolucion { get; set; }

    public int idDesafio { get; set; }

    public int idUsuario { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string ArchivoRuta { get; set; }

    public bool? Publica { get; set; }

    public int? Puntuacion { get; set; }
}