// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class TiposEvaluacion
{
    public int idTipoEvaluacion { get; set; }

    public string Nombre { get; set; }
}