// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class Usuarios
{
    public int idUsuario { get; set; }

    public int idPerfil { get; set; }

    public string NombreUsuario { get; set; }

    public string Contraseña { get; set; }

    public DateTime FechaRegistro { get; set; }

    public int idEstatusUsuario { get; set; }

    public string CorreoElectronico { get; set; }

    public string AvatarURL { get; set; }
}