// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class Vistas
{
    public int idVista { get; set; }

    public int? idVistaPadre { get; set; }

    public string Nombre { get; set; }

    public string URL { get; set; }

    public string ClaseIcono { get; set; }

    public bool EsPrincipal { get; set; }
}