// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CrowdSolve.Server.Entities.CrowdSolve;

public partial class VotosUsuarios
{
    public int idVotoUsuario { get; set; }

    public int idSolucion { get; set; }

    public int idUsuario { get; set; }
}